export const actionTypes = {
  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",

  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAIL: "USER_REGISTER_FAIL",

  USER_PROFILE_UPDATE_REQUEST: "USER_PROFILE_UPDATE_REQUEST",
  USER_PROFILE_UPDATE_SUCCESS: "USER_PROFILE_UPDATE_SUCCESS",
  USER_PROFILE_UPDATE_FAIL: "USER_PROFILE_UPDATE_FAIL",

  USER_PROFILE_DELETE_REQUEST: "USER_PROFILE_DELETE_REQUEST",
  USER_PROFILE_DELETE_SUCCESS: "USER_PROFILE_DELETE_SUCCESS",
  USER_PROFILE_DELETE_FAIL: "USER_PROFILE_DELETE_FAIL",

  USER_PROFILE_REQUEST: "USER_PROFILE_REQUEST",
  USER_PROFILE_SUCCESS: "USER_PROFILE_SUCCESS",
  USER_PROFILE_FAIL: "USER_PROFILE_FAIL",

  USER_LOGOUT_SUCCESS: "USER_LOGOUT_SUCCESS",
};
